var item_data = {
    1:{"name":"Abandonment","levelAmountFormula":"linear10","effectDescription":"+%1% Idle DPS","id":1,"maxLevel":0,"scaling":"linear"}, 
    2:{"name":"Wrath","levelAmountFormula":"linear10","effectDescription":"+%1% Click Damage","id":2,"maxLevel":0,"scaling":"linear"},
    3:{"name":"Time","levelAmountFormula":"linear5","effectDescription":"+%1 Sec Boss timers","id":3,"maxLevel":0,"scaling":"cubic"},
    4:{"name":"Agitation","levelAmountFormula":"linear1","effectDescription":"+%1 Sec Clickstorm","id":4,"maxLevel":0,"scaling":"linear"},
    5:{"name":"Luck","levelAmountFormula":"linear1","effectDescription":"+%1% Double Rubies Chance","id":5,"maxLevel":7,"scaling":"cubic"},
    6:{"name":"Vision","levelAmountFormula":"linear1","effectDescription":"+%1 Starting Zone","id":6,"maxLevel":0,"scaling":"cubic"},
    7:{"name":"Enhancement","levelAmountFormula":"linear1","effectDescription":"+%1% Gild Damage","id":7,"maxLevel":0,"scaling":"linear"},
    8:{"name":"Battery Life","levelAmountFormula":"linear1","effectDescription":"+%1 Sec Metal Detector","id":8,"maxLevel":0,"scaling":"linear"},
    9:{"name":"Thieves","levelAmountFormula":"linear1","effectDescription":"+%1 Sec Golden Clicks","id":9,"maxLevel":0,"scaling":"linear"},
    10:{"name":"Accuracy","levelAmountFormula":"linear1","effectDescription":"+%1 Sec Lucky Strikes","id":10,"maxLevel":0,"scaling":"linear"},
    11:{"name":"Rage","levelAmountFormula":"linear1","effectDescription":"+%1 Sec Powersurge","id":11,"maxLevel":0,"scaling":"linear"},
    12:{"name":"Wallops","levelAmountFormula":"linear1","effectDescription":"+%1 Sec Super Clicks","id":12,"maxLevel":0,"scaling":"linear"},
    13:{"name":"Diseases","levelAmountFormula":"linear1","effectDescription":"-%1% Boss Life","id":13,"maxLevel":7,"scaling":"cubic"},
    14:{"name":"Death","levelAmountFormula":"linear10","effectDescription":"+%1% Hero Soul DPS","id":14,"maxLevel":0,"scaling":"linear"},
    15:{"name":"Murder","levelAmountFormula":"linear1","effectDescription":"+%1% Critical Click Damage","id":15,"maxLevel":0,"scaling":"linear"},
    16:{"name":"Discovery","levelAmountFormula":"linear10","effectDescription":"+%1% Treasure Chests","id":16,"maxLevel":7,"scaling":"cubic"},
    17:{"name":"Souls","levelAmountFormula":"linear1","effectDescription":"+%1% Primal Boss Chance","id":17,"maxLevel":7,"scaling":"cubic"},
    18:{"name":"Chance","levelAmountFormula":"linear0_25","effectDescription":"+%1% 10x Gold Chance","id":18,"maxLevel":7,"scaling":"cubic"},
    19:{"name":"Thrift","levelAmountFormula":"linear1","effectDescription":"-%1% Hero Cost","id":19,"maxLevel":7,"scaling":"cubic"},
    20:{"name":"Wealth","levelAmountFormula":"linear15","effectDescription":"+%1% Golden Clicks Gold","id":20,"maxLevel":0,"scaling":"linear"},
    21:{"name":"Riches","levelAmountFormula":"linear25","effectDescription":"+%1% Treasure Chest Gold","id":21,"maxLevel":0,"scaling":"linear"},
    22:{"name":"Greed","levelAmountFormula":"linear5","effectDescription":"+%1% Gold Dropped","id":22,"maxLevel":0,"scaling":"linear"},
    24:{"name":"Freedom","levelAmountFormula":"libAndSiy","effectDescription":"+%1% Idle Gold","id":24,"maxLevel":0,"scaling":"linear"},
    25:{"name":"Wisdom","levelAmountFormula":"solomonRewards","effectDescription":"+%1% Primal Hero Souls","id":25,"maxLevel":0,"scaling":"cubic"}
};
var rarity_conv = ["Common","Uncommon","Rare","Epic","Fabled","Mythical","Legendary","Transcendent"];